### PR TITLE
Added nexus4-like skin to have a screen big enough for UI testing and…

### PR DESCRIPTION
**Pull request by marinomeneghel**
… keyevent to remove the lockscreen that appears at the first emulator launch

### CODE REVIEW

**Comment by viktorbenei** [comment]
For some reason this breaks the step on OS X:

```
(i) adb: /Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/platform-tools/adb
=> Starting emulator (sys-img-armeabi-v7a-android-23) ...
(i) No running emulator found
os: Darwin
/Users/vagrant/Library/Developer/Xamarin/android-sdk-macosx/tools/emulator -avd sys-img-armeabi-v7a-android-23 -netdelay none -netspeed full -no-boot-anim -skin 768x1280 -noaudio -no-window
/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise970193501/step_src/emulator.rb:224:in `<main>': no serial (RuntimeError)
(i) No running emulator found
```

Works good on Linux! ;)

**Comment by viktorbenei** [comment]
@godrei please have a look on the PR!

**Comment by godrei** [comment]
@marinomeneghel Instead of hard coding the skin, we wired out into a new input :`skin`, see: https://github.com/bitrise-steplib/steps-start-android-emulator/releases/tag/1.0.0

**Comment by marinomeneghel** [comment]
Definitely better, thanks!

**Pull request closed without merging**
