### PR TITLE
godeps-update

### PR DESCRIPTION
**Pull request by trapacska**

### CODE REVIEW

**Comment by trapacska** [comment]
Hey @koral-- !

Just testing the go-android package, and it seems like there is an issue with the `lib64 qt`.

- Linux -  LTS stack:

```
+------------------------------------------------------------------------------+
| (1) Step test                                                                |
+------------------------------------------------------------------------------+
| id: ./                                                                       |
| version:                                                                     |
| collection: path                                                             |
| toolkit: go                                                                  |
| time: 2017-05-26T08:31:40Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[08:31:40] Start installing (golang) with apt-get       
INFO[08:31:40]  * [OK] Step dependency (go) installed, available. 

Configs:
- EmulatorName: android-25-armeabi-v7a
- Skin: 768x1280
- EmulatorOptions: -no-boot-anim -no-window
- AndroidHome: /opt/android-sdk-linux
- WaitForBoot: true
- BootTimeout: 1600

Validate AVD image
AVD image (android-25-armeabi-v7a) exist
failed to get lib64 qt lib path, error: qt lib does not exist at: /opt/android-sdk-linux/tools/lib64/qt/lib

Start AVD image
$ /opt/android-sdk-linux/tools/emulator "-avd" "android-25-armeabi-v7a" "-skin" "768x1280" "-no-boot-anim" "-no-window"

WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:

       - Use the '-force-32bit' option when invoking 'emulator'.
       - Set ANDROID_EMULATOR_FORCE_32BIT to 'true' in your environment.

       Either one will allow you to use the 32-bit binaries, but please be
       aware that these will disappear in a future Android SDK release.
       Consider moving to a 64-bit Linux system before that happens.

Failed to start emultor, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Step test (exit code: 1)                                      | 12 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...ub.com/bitrise-steplib/steps-start-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-start-android-emulator      |
+---+---------------------------------------------------------------+----------+
```

- Linux - Non-LTS stack:
boot timed out

- Mac - Xamarin stack
boot timed out

All of them are armeabi-v7a.

For now I reverting the changes, however feel free to fix the issues and we are always happy to see new PRs.

If you need more info about the failed builds, please ping me on our on-site chat!

**Comment by viktorbenei** [comment]
@trapacska please add a bit more testing comments, how this issue can be reproduced and tested, so that we won't have to revert accepted PRs ;)

Also add some tests to this package, or schedule a revision how this package could be better tested, to prevent PRs from getting merged if it contains an issue like this.

**Comment by koral--** [comment]
OK, I'll investigate that.
Is there any better option to test changes like this apart from copying/overwriting contents of `vendor/github.com/bitrise-tools/go-android/emulatormanager/emulatormanager.go` like I've done here: https://github.com/DroidsOnRoids/steps-start-android-emulator/commit/ca0b178c0e1e7a63e367002b8c64dc96f5984396?

**Comment by viktorbenei** [comment]
> Is there any better option to test changes like this apart from copying/overwriting contents of vendor/github.com/bitrise-tools/go-android/emulatormanager/emulatormanager.go

That's the best solution AFAIK

**Comment by koral--** [comment]
OK, I wondered if there were something like `depman install github.com/bitrise-tools/go-android <git repo url> <commit/branch/tag/refspec>` ;)

> Also add some tests to this package, or schedule a revision how this package could be better tested, to prevent PRs from getting merged if it contains an issue like this.

It seems that there are several steps dependent on `bitrise-tools/go-android`. It should be possible to enumerate them all and run the same workflows which are triggered on their PRs but with replaced `go-android`.

**Comment by viktorbenei** [comment]
Unfortunately no tool like that, although I'd dig that! ;)

For now we're discussing whether the go-android package should live on its own, in a separate repository, or rather move it under one of the android emulator step repos, where changes to it could be easily tested.

**Comment by koral--** [comment]
@viktorbenei I received the logs via on-site chat.

@trapacska indeed `android-25-armeabi-v7a` has a bootloop unlike `android-24-armeabi-v7a`, which I was tested on. It works OOTB on normal (non-LTS) stacks. On Linux LTS stack that image (24) also works after specification explicit SHELL environment variable.
So it seems that a complete solution may be to select specific emulator executable (either manually by adding an explicit input for that and/or let step detect it from AVD config) additionally SHELL env variable may be set. I'll try to test that on all mentioned stacks and ABIs.

**Comment by koral--** [comment]
What is the preferred way to fix issue with undefined `SHELL` variable?
Add `ENV` to Dockerfile or add it only for empulator invocation in go-android? 
Additionally is it fine to hardcode `/bin/bash` here? Technically is not correct but it seems that it is also hardcoded in many places on bitrise.

Regarding the last @trapacska message from on-site chat. The complete solution seems to consist of:

1. Declaring `SHELL` variable on LTS stacks.
2. Using `emulator64-arm` binary on non-LTS stacks (or just always if available) when AVD ABI is `armeabi-v7a`. `mips` and `arm64-v8a` seem to work with `emulator` binary.
3. symlink `kernel-qemu` to `kernel-ranchu` if the latter is missing e.g. in `system-images;android-25;google_apis;arm64-v8a` - this one was not reported by @trapacska but I've encountered it when testing various combinations.

**Comment by viktorbenei** [comment]
> What is the preferred way to fix issue with undefined SHELL variable?

Why do you have to change / set a `SHELL`? Seems dangerous to set it globally to be honest.

> Add ENV to Dockerfile or add it only for empulator invocation in go-android?

Can be, if that env should always be present and it won't cause any issues. Note: you'll also have to set it in the osx playbooks as docker can't be used for running macos (it runs on macos but can't run macos).

> Additionally is it fine to hardcode /bin/bash here? Technically is not correct but it seems that it is also hardcoded in many places on bitrise.

Curious, where is that hardcoded?

> 1. Declaring SHELL variable on LTS stacks.

Only required on the LTS stack? If yes, then I'd add that as an ENV only to the LTS stack's docker image, that seems acceptable.

**Comment by koral--** [comment]
> Why do you have to change / set a SHELL? Seems dangerous to set it globally to be honest.

Here is the reason:

```
WARNING: Cannot decide host bitness because $SHELL is not properly defined; 32 bits assumed.
ERROR: 32-bit Linux Android emulator binaries are DEPRECATED, to use them
       you will have to do at least one of the following:
(...)
```

Legacy emulator uses `SHELL` to guess bitness. When it is not defined it falls back to 32-bit which not usable anymore (even with legacy binaries).
`SHELL` is defined on non-LTS Linux and Xamarin stacks but not defined on Linux LTS stack (haven't checked on Xamarin LTS). Not sure what is responsible for defining it, bash package perhaps? 

> Curious, where is that hardcoded?

Just 2 examples which I spotted recently:
- https://github.com/bitrise-docker/android-ndk-lts/blob/master/system_report.sh#L1
- https://github.com/bitrise-io/steps-script/blob/master/step.yml#L43

> Only required on the LTS stack?

Yes, on non-LTS it is already defined.

**Comment by koral--** [comment]
>  you'll also have to set it in the osx playbooks

It is already set by default, just checked on Xamarin LTS stack.
So only on Android LTS it needs to be added.

**Comment by viktorbenei** [comment]
@koral-- awesome, I guess there MacOS sets that by default, we don't set it ourselves.

What about the non LTS Android stack? Is the SHELL env set there, or simply not needed?

**Comment by koral--** [comment]
The answer is already in my previous comment ;) :
> So only on Android LTS it needs to be added.

**Comment by viktorbenei** [comment]
> The answer is already in my previous comment ;)

Indeed, although the situation is a bit less clear. I just checked and the `SHELL` env is **not** set on any of the linux/android/docker stacks. So

> Legacy emulator uses SHELL to guess bitness.

I'd guess this is right, that the legacy emulator requires the SHELL env

> SHELL is defined on non-LTS Linux and Xamarin stacks but not defined on Linux LTS stack

But this is not correct, `SHELL` is not set/defined on the non-LTS Linux stack (it is on the Xamarin ones, as SHELL is defined by MacOS by default.

**Comment by koral--** [comment]
Right, I was a little bit confused due to all that cases.
And I was checking this way:
```
# docker run -ti --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest echo $SHELL
/bin/bash
```
but it is an incorrect way because just echo is executed under bash (and results are the same on LTS).

So to sum up and resolve any doubts:

1. `SHELL` is not defined explicitly in any Linux stack
2. On non-LTS stack it does not matter
3. On Linux LTS stack `SHELL` needs to added to `emulator` invocation for bitness guess to work

**Comment by viktorbenei** [comment]
Just a correction for

> docker run -ti --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest echo $SHELL

If you run the command this way, it'll expand the `$SHELL` env var **on your Mac/on the host**, not inside the container! The `$X` env var refs are expanded **before** running the command in the Terminal (in the shell/in bash).

To prevent expansion of the env you should either first just start the container and "jump into it" (e.g. `docker run -ti --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest bash`) and run the command there, or use single quotes (I think in this case this would make it work as expected: `docker run -ti --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest echo '$SHELL'` -- single quotes around `$SHELL`).

Yeah, shells are tricky when you want to pass env vars between "hosts" / VMs / containers, we had quite a few issues with expansions (on the right host / VM) too..

**Comment by koral--** [comment]
Right, but I spotted one more thing which can mess up ;)
It seems that running `echo $SHELL` inside bash session will always output `/bin/bash` even if the environment variable is not defined (it is not present in `env` output). This does not happen e.g. with zsh shell.

Examples:
```
root@docker-test:~# docker run --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest env |grep SHELL

root@docker-test:~# docker run --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest bash -c 'echo $SHELL'
/bin/bash

root@docker-test:~# docker run -ti --privileged --volume "$(pwd):/bitrise/src" --volume "/var/run/docker.sock:/var/run/docker.sock" --rm bitriseio/android-ndk:latest bash
root@7f71a23d9dfa:/bitrise/src# echo $SHELL
/bin/bash
root@7f71a23d9dfa:/bitrise/src# env | grep SHELL
root@7f71a23d9dfa:/bitrise/src#
```

**Comment by viktorbenei** [comment]
Indeed, the SHELL env might also be specified / defined by the parent process, e.g. by the bash shell process. Depends on the tools / parent processes (as env vars are passed down from parent-to-child process, unless the parent does not share its envs with the child process).

**Pull request closed without merging**
